[workspace]
authors = ["Ilia Kirianov <crux32@gmail.com>"]
channels = ["conda-forge"]
name = "sandbox"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"
pip = ">=26.1.1,<27"

# Tell pip (inside pixi) which index to use for PyTorch
[pypi-options]
index-url = "https://download.pytorch.org/whl/cu126"

# Declare the pip‑installed packages
[pypi-dependencies]
torch = ">=2.6.0"
torchvision = ">=0.26.0"
torchaudio = ">=2.6.0"
